### ISSUE TITLE
Credentials for SD image

### ISSUE THREAD

**Issue by Dirigibility** [vietanhdev/open-adas#10]
Hi, I read your blogs, wonderful work!
I was able to boot my nano with the image, the app GUI comes up nicely.
Can you please provide us with user creds so I can log in sudo and start tinkering? I can't find it anywhere in the docs.

I'm going to attempt to connect this to my car and run it in production, then tweak it with extra features and submit back to the community.
I would like to extend features such as adding models for specific person detection, security cam functions, automatic parking meter starter etc. It will be fun, I'm new to qt but not to python, and I played a bit with vision AI already.

I am considering converting the ONNX to OpenVino to run on the little Oak with the intel hardware.
So many possibilities! You ROCK!

Thanks.

**Comment by theheadturner** [comment]
> Hi, I read your blogs, wonderful work!
> I was able to boot my nano with the image, the app GUI comes up nicely.
> Can you please provide us with user creds so I can log in sudo and start tinkering? I can't find it anywhere in the docs.
> 
> I'm going to attempt to connect this to my car and run it in production, then tweak it with extra features and submit back to the community.
> I would like to extend features such as adding models for specific person detection, security cam functions, automatic parking meter starter etc. It will be fun, I'm new to qt but not to python, and I played a bit with vision AI already.
> 
> I am considering converting the ONNX to OpenVino to run on the little Oak with the intel hardware.
> So many possibilities! You ROCK!
> 
> Thank you

Hey,

Were you able to write the image on a 64 GB card or 128 GB ?? Please confirm.

I am not able to write on my 64 GB.

**Comment by Dirigibility** [comment]
I installed on a 128 GiB SD so no borderline size issues due to different SD card sizes, I would suggest you do the same.

Still I will need the password for user smartcam, assuming it's in sudoers.

**Comment by vietanhdev** [comment]
Sorry. I forgot the password. Have you tried 12345678, 1111, 1 ? Or you can type `sudo passwd smartcam` from command line to see if you can change the password.

**Comment by aatifd** [comment]
Hi vietanhdev,

Can you please share me the image password, i'm unable to login. Thank you in advance

**Comment by Dirigibility** [comment]
root
No password
