### ISSUE TITLE
Login and password

### ISSUE THREAD

**Issue by thomas-pegot** [vietanhdev/open-adas#11]
Hello,

For the binary, is it possible to get Jarvis Login and password ?

Or maybe it's written somewhere I didn't notice.

Thanks

PS: I can actually open a terminal with privilege so it's ok

**Comment by vietanhdev** [comment]
Please type the following in Terminal to check if you can change the password.
```
sudo passwd smartcam
```
I'm looking forward to see the result from you.

**Comment by thomas-pegot** [comment]
Yes that's the first thing I did and it worked.
Next I had to `vncpasswd` for the headless.
Ty
