### ISSUE TITLE
Calling isShapeTensor before the entire network is constructed may result in an inaccurate result

### ISSUE THREAD

**Issue by ahsanmalik1010** [vietanhdev/open-adas#15]
Getting this error on running the ./CarSmartCam after building the project

`&&&& RUNNING TrafficSignClassifier # 
Creating a new engine file at: models/traffic_sign/traffic_sign_classification_resnet18_64.engine
[04/10/2021-20:57:16] [W] [TRT] Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
Killed
`

**Comment by vietanhdev** [comment]
Hi,You may want to check if your Jetson Nano is 4GB-RAM version. Otherwise, you may not have enough RAM to convert models to TensorRT engines.I recommend using my converted models on the SD card image.

**Comment by electron64** [comment]
I have the same issue, using the SD card image and last code.

**Comment by openbsod** [comment]
Same here with that issue, code updated and successfully builded, models was copied from SD card image.
