### ISSUE TITLE
Argument List 

### ISSUE THREAD

**Issue by Adilhossain227** [vietanhdev/open-adas#16]
Can i get specific argument list so that i can see what else can be tuned. And is there any argument for running from Camera source?

**Comment by vietanhdev** [comment]
I updated the argument list and add documentation in README.md in [the latest commit](https://github.com/vietanhdev/open-adas/commit/0927fc38a3c071f8d4fe5c81137b961696570a50) on `master` branch.

**Comment by Adilhossain227** [comment]
Can I please get an idea , how can I run this in webcam data ? Am now sure from the documentation how to do it.

**Comment by vietanhdev** [comment]
I understand that you're satisfied with the result?

**Comment by Adilhossain227** [comment]
sorry i meant , i am not sure how to run this on webcam data. But the simulation results are impressive.

**Comment by vietanhdev** [comment]
Just use: `./OpenADAS --input_source=video`.
The system needs to be calibrated and have a source of speed (maybe from your vehicle) to work properly.

**Resources:**
- [How to calibrate the camera](https://github.com/vietanhdev/open-adas/blob/master/docs/open-adas.md#2-how-to-calibrate-the-camera)
-  [How to get car sensors](https://github.com/vietanhdev/open-adas/blob/master/docs/open-adas.md#1-how-to-get-car-sensors-speed-turn-signal)

**Comment by Adilhossain227** [comment]
Thanks a lot man ❤️
