### ISSUE TITLE
help

### ISSUE THREAD

**Issue by asoftake** [vietanhdev/open-adas#17]
./OpenADAS —input_source 

GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1

![FA1FAF37-95FC-41C3-A398-685A52355FED](https://user-images.githubusercontent.com/76768873/120195603-930a5700-c251-11eb-8b83-a24cc812112a.jpeg)

**Comment by vietanhdev** [comment]
You should specify a "input_source".

**Comment by asoftake** [comment]
> You should specify an "input_source".

input_source=video 

GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1

**Comment by asoftake** [comment]
> You should specify an "input_source".

![Uploading 5D256A32-52D2-474C-9281-2E665AB8AFF5.jpeg…]()

**Comment by vietanhdev** [comment]
Please read the instruction in README carefully. There is no "video" input_source.
Link: <https://github.com/vietanhdev/open-adas>.

--input_source | default: simulation : Input source. 'camera' or 'simulation'.

**Comment by asoftake** [comment]
--input_source=camera,  There is still no solution.

**Comment by asoftake** [comment]
> Please read the instruction in README carefully. There is no "video" input_source.
> Link: https://github.com/vietanhdev/open-adas.
> 
> --input_source | default: simulation : Input source. 'camera' or 'simulation'.

--input_source=camera, There is still no solution.
![1164DBE7-7251-42DA-962D-E7D03C7F0083](https://user-images.githubusercontent.com/76768873/120306761-c6f28480-c304-11eb-872e-2e17cabbb041.jpeg)

**Comment by vietanhdev** [comment]
Have you checked the version of CUDA and TensorRT? Which platform do you use to run this program? (Inference machine).

**Comment by asoftake** [comment]
> Have you checked the version of CUDA and TensorRT? Which platform do you use to run this program? (Inference machine).

Your car-smart-cam-2020-21-12.zip 
![CFCC38C2-8DA3-4EFD-932D-CF82B35A34B3](https://user-images.githubusercontent.com/76768873/120325742-8aca1e80-c31a-11eb-9573-e385f4aff3f1.jpeg)

**Comment by vietanhdev** [comment]
Do you use it with a 4GB or 2GB RAM Jetson Nano?

**Comment by asoftake** [comment]
> Do you use it with a 4GB or 2GB RAM Jetson Nano?

Jetson Nano 4GB

**Comment by vietanhdev** [comment]
In order to help you determine the problem here, I want to know some more questions:
- After flashing the image, what did you do? (step-by-step).
- Have you run the demo successfully with simulation? (default setup).

**Comment by asoftake** [comment]
> In order to help you determine the problem here, I want to know some more questions:
> 
> * After flashing the image, what did you do? (step-by-step).
> * Have you run the demo successfully with simulation? (default setup).

![3F7F513F-B180-4AF5-865D-FFC713715A21](https://user-images.githubusercontent.com/76768873/120392410-09e34500-c363-11eb-94ec-f2a844c19a01.jpeg)
1:
Red:After flashing the images error information.
Blue: I Alt+F4 to exit the GUI information.

2:   I run the demo successfully with simulation.(./OpenADAS)

**Comment by vietanhdev** [comment]
The version on SD card image does not support camera input. You should pull the latest source code and try again.

**Comment by asoftake** [comment]
> The version on SD card image does not support camera input. You should pull the latest source code and try again.

It's the latest version and the problem hasn't been solved.

**Comment by vietanhdev** [comment]
Have you run "git pull origin master" to get the latest source code, and `cd build && make` to rebuild?

**Comment by asoftake** [comment]
> Have you run "git pull origin master" to get the latest source code, and `cd build && make` to rebuild?

yes，git clone , and cd build && make

**Comment by vietanhdev** [comment]
I haven't known what's wrong on your side. You can check your camera by reading it with other source code or programs.

**Comment by asoftake** [comment]
> I haven't known what's wrong on your side. You can check your camera by reading it with other source code or programs.

TensorRT 6.0.1 , CUDA 10.0

**Comment by asoftake** [comment]
> I haven't known what's wrong on your side. You can check your camera by reading it with other source code or programs.

Warning: Camera hasn’t been calibrated yet.please calibrate your camera to enable safety  features.

**Comment by vietanhdev** [comment]
Please refer to my blog posts and documentation for camera calibration: 
- **(Blog) Intro and Hardware:** <https://aicurious.io/posts/adas-jetson-nano-intro-and-hardware/>.
- **(Blog) Software stack**: <https://aicurious.io/posts/adas-jetson-nano-software/>.
- **(Blog) Deep neural networks:** <https://aicurious.io/posts/adas-jetson-nano-deep-neural-networks/>.
- **(Documentation) OpenADAS:** *Design, CANbus, Calibration, Model training and deployment notes*: [docs/open-adas.md](docs/open-adas.md).
