### ISSUE TITLE
Questions about the project

### ISSUE THREAD

**Issue by poornimajd** [vietanhdev/open-adas#9]
Hello,
A great project! I am also trying to do something similar on a edge compute.I had the following questions-

1.What is the overall fps of your pipeline on jetson Nano.
2.Since you have multiple models, are you loading them in parallel in a single Jetson using some sort of multi-threading?
Basically I just wanted to know if you do a sequential loading of the multiple models and infer or is there any other optimization other than the tensorRT optimization?

Thank you

**Comment by vietanhdev** [comment]
Hello,
Thank you for your interest.
1, As I remember, the overall FPS on Jetson Nano is only ~1x FPS.
2,3, The model loading is sequential. However, the inference is multithreading.

**Comment by poornimajd** [comment]
If you are using multi threading for inference,the model still needs to use the gpu right? So does this bring down the fps of the overall pipeline,because multiple models are sharing the gpu at the same time?

Thanks a lot for the reply.

**Comment by vietanhdev** [comment]
Yes, running multiple models brings down the FPS a lot. 
You can have a much better FPS when running them separately.
